### ISSUE TITLE
odd forcing of data duplication

### ISSUE THREAD

**Issue by cordoval** [rollerworks/datagrid#31]
suppose i have persons going through a flow

and A becomes an applicant and B becomes a business object inside

because i need to be doing grids for both, this library does not like when i have to mix grids that contain columns from A and from B, so i cannot do joins or what not.

Why this limitation was posed in the first place? Since this is a grid why the field_mapping makes it sound like implementing this is very hard?

i believe it will force things to be passed as arrays but then what about lazy loading or proxies in doctrine ..., a bit frustrated with this ... :blush:

**Comment by cordoval** [comment]
bump @sstok :+1:

**Comment by sstok** [comment]
Not sure I'm following correctly, you can easily use Joins for Doctrine or lazy loading.
The data you provide like say an invoice, which has a related customer can be rendered from both.
As long as the base information provided access to the relational object.

If you want to provide both, where there is no defined relation between the two you need to use a custom data-mapper or `DatagridEvents::PRE_SET_DATA` where the data transformed to `[[object-parent 1, child-object2]]` and you define the property-path as `[0].propertName` and `[0].propertName` respectively.


I'm not aware of any other datagrid library that actually supports passing in more then a single collection. Can you point me to one so I can see if there is an easier way to solve this?

**Comment by cordoval** [comment]
closing, thanks for the answer
